#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on xenial-queens."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    # Tempest is installed through pip so cloud archive is not needed here
    deployment = TempestBasicDeployment(series='xenial',
                                        openstack='cloud:xenial-queens',
                                        source='cloud:xenial-updates/queens')
    deployment.run_tests()
