#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on cosmic-rocky."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    deployment = TempestBasicDeployment(series='cosmic')
    deployment.run_tests()

