#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on xenial-newton."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    # Tempest is installed through pip so cloud archive is not needed here
    deployment = TempestBasicDeployment(series='xenial',
                                        openstack='cloud:xenial-newton',
                                        source='cloud:xenial-updates/newton')
    deployment.run_tests()
