#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on zesty-ocata."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    deployment = TempestBasicDeployment(series='zesty')
    deployment.run_tests()

