#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on yakkety-newton."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    deployment = TempestBasicDeployment(series='yakkety')
    deployment.run_tests()

