#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on bionic-train."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    # Tempest is installed through pip so cloud archive is not needed here
    deployment = TempestBasicDeployment(series='bionic',
                                        openstack='cloud:bionic-train',
                                        source='cloud:bionic-train')
    deployment.run_tests()
