#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on xenial-mitaka."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    deployment = TempestBasicDeployment(series='xenial')
    deployment.run_tests()

