#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on trusty-icehouse."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    deployment = TempestBasicDeployment(series='trusty')
    deployment.run_tests()

