#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on trusty-kilo."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    # Tempest is installed through pip so cloud archive is not needed here
    deployment = TempestBasicDeployment(series='trusty',
                                        openstack='cloud:trusty-kilo',
                                        source='cloud:trusty-updates/kilo')
    deployment.run_tests()
