#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on bionic-queens."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    deployment = TempestBasicDeployment(series='bionic')
    deployment.run_tests()

