#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on disco-stein."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    deployment = TempestBasicDeployment(series='disco')
    deployment.run_tests()

