#!/usr/bin/env python

"""Amulet tests on a basic tempest deployment on artful-pike."""

from basic_deployment import TempestBasicDeployment

if __name__ == '__main__':
    deployment = TempestBasicDeployment(series='artful')
    deployment.run_tests()

